LegacyProject/LegacyProject/Controllers/AddressController.cs
using Persistence.Entities;
using Persistence.Repository;
using System;
using System.Net;
using System.Web.Mvc;
using Persistence.Validation;
using Service;
using Service.Validation;

namespace LegacyProject.Controllers
{
    public class AddressController : Controller
    {
        private readonly AddressRepository _addressRepository;
        private readonly AddressService _addressService;

        public AddressController(AddressRepository addressRepository, AddressService addressService)
        {
            _addressRepository = addressRepository;
            _addressService = addressService;
        }
        public ActionResult Index()
        {
            var addresses = _addressRepository.All();
            _addressService.SetDeletable(addresses);
            return View(addresses);
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = _addressRepository.Find(id.Value);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Address address)
        {
            var validation = new AddressValidation(address);
            validation.Validate();

            if (validation.HasError)
            {
                foreach (var errorDescription in validation.Errors)
                {
                    ModelState.AddModelError(errorDescription.Field, errorDescription.Error);
                }
            }
            else
            {
                try
                {
                    _addressService.Create(address);
                }
                catch (FieldValidationException error)
                {
                    ModelState.AddModelError(error.Field, error.Error);
                }
            }
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            return View(address);
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Address address = _addressRepository.Find(id.Value);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Address address)
        {
            var error = EditAddressValidator.NotHasZeroErrors(address, out var errField);
            if (!error && !error && ModelState.IsValid)
            {
                _addressRepository.Update(address);
                return RedirectToAction("Index");
            }
            if (errField != null)
            {
                ModelState.AddModelError(errField, "Fehler bei Eingabe des Feldes!");
            }
            return View(address);
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var address = _addressRepository.Find(id.Value);
            if (address == null)
            {
                return HttpNotFound();
            }
            return View(address);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            _addressRepository.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

LegacyProject/LegacyProject/Controllers/CustomersController.cs
using Persistence.Entities;
using Persistence.Repository;
using System;
using System.Net;
using System.Web.Mvc;

namespace LegacyProject.Controllers
{
    public class CustomersController : Controller
    {
        private readonly CustomerRepository _customerRepository;
        private readonly AddressRepository _addressRepository;

        public CustomersController(
            CustomerRepository customerRepository,
            AddressRepository addressRepository
        )
        {
            _customerRepository = customerRepository;
            _addressRepository = addressRepository;
        }


        // GET: Customers
        public ActionResult Index()
        {
            return View(_customerRepository.All());
        }

        // GET: Customers/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = _customerRepository.Find(id.Value);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {
            if (customer.CustomerFirstname == "")
            {
                ModelState.AddModelError("CustomerFirstname", "Bitte geben Sie einen Vornamen ein!");
            }
            if (customer.CustomerSurname == "")
            {
                ModelState.AddModelError("CustomerFirstname", "Bitte geben Sie einen Nachnamen ein!");
            }

            if (ModelState.IsValid)
            {
                _customerRepository.Add(customer);
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = _customerRepository.Find(id.Value);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer customer)
        {
            if (customer.CustomerFirstname == "")
            {
                ModelState.AddModelError("CustomerFirstname", "Bitte geben Sie einen Vornamen ein!");
            }
            if (customer.CustomerSurname == "")
            {
                ModelState.AddModelError("CustomerFirstname", "Bitte geben Sie einen Nachnamen ein!");
            }

            if (ModelState.IsValid)
            {
                _customerRepository.Update(customer);
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = _customerRepository.Find(id.Value);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            _customerRepository.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

LegacyProject/LegacyProject/Views/Customers/Create.cshtml
@model Persistence.Entities.Customer

@{
    ViewBag.Title = "Kunde anlegen";
}

<h2>Kunde anlegen</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kunde</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerFirstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerFirstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerFirstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerSurname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerSurname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerSurname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Erstellen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LegacyProject/LegacyProject/Views/Customers/Delete.cshtml
@model Persistence.Entities.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Kunde löschen</h2>

<h3>Sind Sie sich sicher?</h3>
<div>
    <h4>Kunde</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerFirstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerFirstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerSurname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerSurname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Löschen" class="btn btn-default" /> |
            @Html.ActionLink("Zurück", "Index")
        </div>
    }
</div>

LegacyProject/LegacyProject/Views/Customers/Details.cshtml
@model Persistence.Entities.Customer

@{
    ViewBag.Title = "Details";
}

<h2>Kundendetails</h2>

<div>
    <h4>Kundendetails</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerFirstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerFirstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerSurname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerSurname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress.StreetText)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerAddress.StreetText)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress.Zip)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerAddress.Zip)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerAddress.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerAddress.Country)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Bearbeiten", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Adresse", "Details", "Address", new { id = Model.CustomerAddress.Id }, null) |
    @Html.ActionLink("Lieblingsshop", "Details", "FavouriteShop", new { id = Model.Id }, null) |
    @Html.ActionLink("Zurück", "Index")
</p>

LegacyProject/LegacyProject/Views/Customers/Edit.cshtml
@model Persistence.Entities.Customer

@{
    ViewBag.Title = "Kunde bearbeiten";
}

<h2>Kunde bearbeiten</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Kunde</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerFirstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerFirstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerFirstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerSurname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerSurname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerSurname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Speichern" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Adresse", "Details", "Address", new { id = Model.CustomerAddress.Id }, null) |
        @Html.ActionLink("Lieblingsshop", "Details", "FavouriteShop", new { id = Model.Id }, null) |
        @Html.ActionLink("Zurück", "Index")
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LegacyProject/LegacyProject/Views/Customers/Index.cshtml
@model IEnumerable<Persistence.Entities.Customer>

@{
    ViewBag.Title = "Kunden";
}

<h2>Kunden</h2>

<p>
    @Html.ActionLink("Neu erstellen", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerFirstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerSurname)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr style="color: @(item.CustomerType=="red"?"pink":"black")">
        <td>
            @Html.DisplayFor(modelItem => item.CustomerFirstname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerSurname)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Adresse", "Details", "Address", new { id = item.CustomerAddress?.Id }, null) |
            
            @Html.ActionLink("Lieblingsshop", "Details", "FavouriteShop", new { id = item.Id }, null) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>